### ISSUE TITLE
关于云编译有自带插件的问题

### ISSUE THREAD

**Issue by skycn3322** [danshui-git/shuoming#1]
你好，我用了你的自动编译脚本后感觉整个流程都简单很多，但有个问题一直困扰着我，就是在云编译过程中我已经去掉了SSR-PLUS、迅雷快鸟、UU游戏加速、去广告大师等插件，但是在云编译成功后这些插件依然在编译好的固件内，请问有什么方法可以避免吗？目前想到的办法是用rm -rf来解决，有没有更快速的办法呢？

**Comment by danshui-git** [comment]
固件需要什么插件，不是用rm -rf来解决，是编译的时候打开SSH连接，配置固件，在里面可以设置什么要的，什么不要的，编译完成后会有一份.config的配置文件，你复制里面的内容粘贴内容覆盖到你编译使用的文件夹里的.config里面就可以保存配置了，不更改插件的情况下不需要再次SSH
