### ISSUE TITLE
关于使用Telegram Bot来实现推送通知的问题

### ISSUE THREAD

**Issue by skycn3322** [danshui-git/shuoming#2]
获取到json数据："message":{"message_id":182,"from":{"id":18061xxxxx,"is_bot":false,唯独is_bot数据为：false,目前用的消息推送都是user_id+token实现的，现在chat_id好像已经行不通了，能否修改代码实现使用user_id+token来实现消息推送呢？

**Comment by danshui-git** [comment]
测试了，推送消息是没问题的，自己看看那里搞错了吧
