### ISSUE TITLE
请问如何能验证本地拉去的代码没有丢失?

### ISSUE THREAD

**Issue by wszgrcy** [danshui-git/shuoming#3]
云编译确实好,但是现在还没有成功的编译一遍,属于debug阶段(之前成功编译过了....但是配置忘备份了)
每次编译都会或多或少的出一点bug,要么是xxxundefined,要么是编译成功后network页面接口500.不知道是代码拉取问题还是bug,还是自己没配置好...所以想先排除下是不是代码拉取是否完整.每次都拉好几遍保证,但是好像还是有点不对劲.......

**Comment by danshui-git** [comment]
请不要在这里提问，我看不到，也不收信息，云编译不需要验证什么代码完整不完整，基本100%不会出错的，如果是本地编译就难说了，这个跟你的翻墙节点有关系，有写节点简直就是不止所谓的，上油管速度飞快，但是用来编译就很经常少拉源码啊，编译不成功什么的
